# Generated by Django 3.0.5 on 2025-01-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='img_avatar',
            field=models.ImageField(default='avatar_images/default-avatar-profile-icon-of-social-media-user-vector.jpg', null=True, upload_to='avatar_images/'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='img_background',
            field=models.ImageField(blank=True, null=True, upload_to='background_images/'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='img_background_position',
            field=models.IntegerField(default=0),
        ),
    ]
