# Generated by Django 3.0.5 on 2025-01-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20250117_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='img_avatar',
            field=models.CharField(blank=True, default='https://i.imgur.com/default-avatar.jpg', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='img_background',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
