# Generated by Django 3.1.12 on 2025-01-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
