# Generated by Django 3.1.12 on 2025-01-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20250123_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.URLField(blank=True, default='https://i.imgur.com/OJbZSFy.jpeg', null=True),
        ),
    ]
