# Generated by Django 3.1.12 on 2025-02-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0003_auto_20250201_1922'),
        ('book', '0003_auto_20250124_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_team', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributors.team')),
            ],
            options={
                'unique_together': {('book', 'team')},
            },
        ),
    ]
