# Generated by Django 3.1.12 on 2025-03-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20250305_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volume',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='volume',
            name='number',
        ),
    ]
