# Generated by Django 3.1.12 on 2025-02-01 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0003_auto_20250201_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamType',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='contributors.teamtype'),
        ),
    ]
